<a href="https://colab.research.google.com/github/vinceyvincey/ml_fundamentals/blob/main/notebook_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Flow 2.0 Introduction


In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
string = tf.Variable("this is a variable",tf.string)
print(string)

In [7]:
number = tf.Variable(324, tf.int16)
print(number)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [9]:
floating = tf.Variable(3.567, tf.float64)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [10]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>


In [11]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>


In [12]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [18]:
tensor2 = tf.reshape(tensor1,[1,3,2])
print(tensor2)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(1, 3, 2), dtype=float32)


In [19]:
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [21]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

print(matrix)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [22]:
tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tensor)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>


In [23]:
print(tensor.shape)

(4, 5)
